package com.seal.provider.model.domain;

import java.util.Date;

public class ApplyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_detail.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_detail.special_business_approval_id
     *
     * @mbg.generated
     */
    private String specialBusinessApprovalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_detail.apply_info
     *
     * @mbg.generated
     */
    private String applyInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_detail.id
     *
     * @return the value of apply_detail.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_detail.id
     *
     * @param id the value for apply_detail.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_detail.special_business_approval_id
     *
     * @return the value of apply_detail.special_business_approval_id
     *
     * @mbg.generated
     */
    public String getSpecialBusinessApprovalId() {
        return specialBusinessApprovalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_detail.special_business_approval_id
     *
     * @param specialBusinessApprovalId the value for apply_detail.special_business_approval_id
     *
     * @mbg.generated
     */
    public void setSpecialBusinessApprovalId(String specialBusinessApprovalId) {
        this.specialBusinessApprovalId = specialBusinessApprovalId == null ? null : specialBusinessApprovalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_detail.create_time
     *
     * @return the value of apply_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_detail.create_time
     *
     * @param createTime the value for apply_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_detail.apply_info
     *
     * @return the value of apply_detail.apply_info
     *
     * @mbg.generated
     */
    public String getApplyInfo() {
        return applyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_detail.apply_info
     *
     * @param applyInfo the value for apply_detail.apply_info
     *
     * @mbg.generated
     */
    public void setApplyInfo(String applyInfo) {
        this.applyInfo = applyInfo == null ? null : applyInfo.trim();
    }
}