package com.seal.provider.mapper;

import com.seal.provider.model.domain.ApplyDetail;

public interface ApplyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_detail
     *
     * @mbg.generated
     */
    int insert(ApplyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_detail
     *
     * @mbg.generated
     */
    int insertSelective(ApplyDetail record);
}